[core]
reloadable = true

display_name = "Synthetic Perception"

[package]
title="Synthetic Perception"
description="Synthetic Perception desc"
category=""
authors=['Jon']
keywords=['custom']

[dependencies]
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.syntheticdata" = {}

[[python.module]]
name = "com.SyntheticPerception.app"


[[native.plugin]]
recursive = false
